name: Build & Release StreamFlix

on:
  workflow_dispatch: # manual trigger from Actions tab

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # no macOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Move artifacts to builds folder
        run: |
          mkdir -p builds/${{ matrix.os }}
          mv dist/* builds/${{ matrix.os }}/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StreamFlix-${{ matrix.os }}
          path: builds/${{ matrix.os }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: builds

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: manual-${{ github.run_number }}
          name: Manual Release ${{ github.run_number }}
          files: builds/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
